### PR TITLE
Use new Campaign integration method

### PR DESCRIPTION
**Pull request by bencroker**
I've made it easier to integrate with the Campaign plugin going forward. This PR uses the new `FormsService::createAndSubscribeContact` method, falling back to the manual way of doing things if the method does not exist (if an older version of Campaign is installed). I also added a `TODO` to remind you to remove the manual approach in the next major version of Freeform.

### CODE REVIEW

**Comment by kjmartens** [comment]
Thanks @bencroker. We'll check into it. 🙂 

Just to confirm, this only applies to Campaign 2 for Craft 4, therefore only Freeform 4 for Craft 4?

**Comment by bencroker** [comment]
That's correct, Kelsey. Hopefully I PR'd into the correct branch?

**Comment by kjmartens** [comment]
You PR'd the FF3 branch, but no worries... we'll sort it out. Thanks for the for assistance. 🙂

**Comment by bencroker** [comment]
Ah, my mistake, I'll correct it, but what is the best branch to use, `5.0`?

**Comment by kjmartens** [comment]
v4.0/master 🙂

**Comment by bencroker** [comment]
Closing in favour of https://github.com/solspace/craft-freeform/pull/412

**Pull request closed without merging**
